server:
  port: 9081
  serverId: config-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.7:9080/eureka/
    healthcheck:
      enabled: true
  instance:
    appname: config-server
    prefer-ip-address: true


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lyzh04061135/spring-cloud-config.git
          search-paths: config-server
          username: lyzh04061135
          password: l2013githubyzh
          force-pull: true
      label: master
  profiles:
    active: git

demo:
  config:
    server:
      name: config-server

logging:
  level:
    com:
      demo: debug
